
-- 备份表
INSERT INTO `YOUR_TABLE_BACKUP` SELECT * FROM `YOUR_TABLE` WHERE ;

-- 删除备份表的索引，减少磁盘占用
ALTER TABLE `YOUR_TABLE_BACKUP` DROP KEY `YOUR_TABLE_INDEX`;

-- 回收表预分配空间
OPTIMIZE TABLE YOUR_TABLE;

-- 清空老表
TRUNCATE TABLE `YOUR_OLD_TABLE`;

-- 按条件清除旧数据
DELETE FROM `t_src_aqi_data` WHERE `` < 1704038400000;
